name: Validate renovate config

on:
  pull_request:
    paths:
      - "renovate.json"
      - ".github/workflows/validate-renovate.yml"

jobs:
  validate-renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Validate
        run: npx --package renovate -c 'renovate-config-validator'
